export const PRESETS = [
  {
    id: 'rose',
    name: 'Rose Nocturne',
    color: '#F5E6E8',
    liquidColor: '#8B2942',
    capColor: '#D4AF37',
    capType: 'dome',
    capFinish: 'gold',
    bottleType: 'elegant',
    bottleSource: 'glb',
    environment: 'sunset',
    bgMode: 'warm',
    liquidLevel: 0.72,
    bottleShine: 0.4,
    fragranceName: 'ROSE NOCTURNE',
    volumeMl: 50,
    showFragranceLabel: true,
    showEngraving: true,
    engravingText: 'ROSE NOCTURNE',
    engravingFont: 'serif',
    engravingColor: '#D4AF37',
  },
  {
    id: 'noir',
    name: 'Noir Intense',
    color: '#1A1A1A',
    liquidColor: '#2C1810',
    capColor: '#1A1A1A',
    capType: 'modern',
    capFinish: 'matte',
    bottleType: 'square',
    bottleSource: 'glb',
    environment: 'warehouse',
    bgMode: 'dark',
    liquidLevel: 0.55,
    bottleShine: 0.1,
    fragranceName: 'NOIR INTENSE',
    volumeMl: 100,
    showFragranceLabel: true,
    showEngraving: true,
    engravingText: 'NOIR',
    engravingFont: 'sans',
    engravingColor: '#C0C0C0',
  },
  {
    id: 'or',
    name: 'Or Impérial',
    color: '#F5F0EB',
    liquidColor: '#C9A962',
    capColor: '#D4AF37',
    capType: 'classic',
    capFinish: 'gold',
    bottleType: 'vintage',
    bottleSource: 'glb',
    environment: 'lobby',
    bgMode: 'warm',
    liquidLevel: 0.80,
    bottleShine: 0.5,
    fragranceName: 'OR IMPÉRIAL',
    volumeMl: 75,
    showFragranceLabel: true,
    showEngraving: true,
    engravingText: 'OR IMPÉRIAL',
    engravingFont: 'serif',
    engravingColor: '#D4AF37',
  },
  {
    id: 'ocean',
    name: 'Océan Clair',
    color: '#E8F4F8',
    liquidColor: '#1B6B93',
    capColor: '#C0C0C0',
    capType: 'dome',
    capFinish: 'silver',
    bottleType: 'slender',
    bottleSource: 'glb',
    environment: 'dawn',
    bgMode: 'white',
    liquidLevel: 0.65,
    bottleShine: 0.3,
    fragranceName: 'OCÉAN',
    volumeMl: 50,
    showFragranceLabel: true,
    showEngraving: false,
    engravingText: 'OCÉAN',
    engravingFont: 'sans',
    engravingColor: '#1B6B93',
  },
  {
    id: 'amber',
    name: 'Ambre Signature',
    color: '#FFF8E7',
    liquidColor: '#D4760A',
    capColor: '#8B6914',
    capType: 'classic',
    capFinish: 'gold',
    bottleType: 'round',
    bottleSource: 'glb',
    environment: 'city',
    bgMode: 'midnight',
    liquidLevel: 0.78,
    bottleShine: 0.45,
    fragranceName: 'AMBRE',
    volumeMl: 50,
    showFragranceLabel: true,
    showEngraving: true,
    engravingText: 'AMBRE',
    engravingFont: 'serif',
    engravingColor: '#D4760A',
  },
  {
    id: 'minimal',
    name: 'Blanc Pur',
    color: '#FFFFFF',
    liquidColor: '#E8E8E8',
    capColor: '#FFFFFF',
    capType: 'modern',
    capFinish: 'matte',
    bottleType: 'hexagonal',
    bottleSource: 'glb',
    environment: 'studio',
    bgMode: 'white',
    liquidLevel: 0.60,
    bottleShine: 0.15,
    fragranceName: 'BLANC PUR',
    volumeMl: 30,
    showFragranceLabel: true,
    showEngraving: false,
    engravingText: 'BLANC',
    engravingFont: 'sans',
    engravingColor: '#888888',
  },
];
